INSERT INTO cms_pages (slug, title, subtitle, content, seo) VALUES
  ('home',                'Wujudkan Potensi Terbaikmu',         'Platform pendidikan terbaik untuk karir dan wirausaha', '{}', '{"metaTitle":"VernonEdu - Platform Pendidikan Karir & Wirausaha","metaDescription":"Tingkatkan skill dan karir Anda bersama VernonEdu","ogImage":""}'),
  ('program-karir',       'Program Karir',                      'Persiapan karir profesional yang komprehensif',         '{}', '{"metaTitle":"Program Karir - VernonEdu","metaDescription":"Program karir terbaik untuk mempersiapkan masa depan Anda","ogImage":""}'),
  ('program-reguler',     'Program Reguler',                    'Kursus reguler berkualitas tinggi',                     '{}', '{"metaTitle":"Program Reguler - VernonEdu","metaDescription":"Kursus reguler dengan kurikulum terkini","ogImage":""}'),
  ('program-privat',      'Program Privat',                     'Belajar privat dengan mentor berpengalaman',            '{}', '{"metaTitle":"Program Privat - VernonEdu","metaDescription":"Belajar intensif dengan mentor profesional","ogImage":""}'),
  ('program-sertifikasi', 'Program Sertifikasi',                'Raih sertifikasi kompetensi yang diakui industri',      '{}', '{"metaTitle":"Program Sertifikasi - VernonEdu","metaDescription":"Sertifikasi kompetensi profesional","ogImage":""}'),
  ('untuk-universitas',   'Kolaborasi dengan Universitas',      'Program kolaborasi khusus mahasiswa universitas',        '{}', '{"metaTitle":"Program Universitas - VernonEdu","metaDescription":"Tingkatkan kompetensi mahasiswa bersama VernonEdu","ogImage":""}'),
  ('untuk-sekolah',       'Kolaborasi dengan Sekolah',          'Program pengembangan skill untuk pelajar',               '{}', '{"metaTitle":"Program Sekolah - VernonEdu","metaDescription":"Program skill building untuk pelajar SMA","ogImage":""}'),
  ('untuk-korporat',      'In-House Training Korporat',         'Pelatihan karyawan yang disesuaikan kebutuhan bisnis',   '{}', '{"metaTitle":"In-House Training - VernonEdu","metaDescription":"Tingkatkan kompetensi tim Anda dengan pelatihan korporat","ogImage":""}'),
  ('untuk-individu',      'Program Individual',                 'Belajar sesuai jadwal dan kebutuhan Anda',               '{}', '{"metaTitle":"Program Individual - VernonEdu","metaDescription":"Belajar fleksibel sesuai kebutuhan Anda","ogImage":""}')
ON CONFLICT (slug) DO NOTHING;
