ALTER TABLE course_types
  ADD COLUMN IF NOT EXISTS normal_price     BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_price        BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_participants INT    NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_participants INT    NOT NULL DEFAULT 0;
