package calendar

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

var (
	ErrCalendarEventNotFound      = errors.New("calendar event not found")
	ErrAutoGeneratedEventReadOnly = errors.New("auto-generated events are read-only")
)

type EventType string

const (
	EventTypeClassSession        EventType = "class_session"
	EventTypeStaffMeeting        EventType = "staff_meeting"
	EventTypeAdminDeadline       EventType = "admin_deadline"
	EventTypePaymentDue          EventType = "payment_due"
	EventTypeFacilitatorSchedule EventType = "facilitator_schedule"
	EventTypePartnerMeeting      EventType = "partner_meeting"
)

type CalendarEvent struct {
	ID             uuid.UUID
	Title          string
	Description    *string
	EventType      EventType
	StartAt        time.Time
	EndAt          time.Time
	IsAllDay       bool
	RecurrenceRule *string
	Location       *string
	SourceDomain   *string
	SourceID       *uuid.UUID
	CreatedBy      uuid.UUID
	CreatedAt      time.Time
}

func (e *CalendarEvent) IsManual() bool {
	return e.SourceDomain == nil
}

type WriteRepository interface {
	Save(ctx context.Context, e *CalendarEvent) error
	Update(ctx context.Context, e *CalendarEvent) error
	Delete(ctx context.Context, id uuid.UUID) error
}

type ReadRepository interface {
	ListByMonth(ctx context.Context, year, month int) ([]*CalendarEvent, error)
	GetByID(ctx context.Context, id uuid.UUID) (*CalendarEvent, error)
}
