package delete_calendar_event

import (
	"context"

	"github.com/rs/zerolog/log"

	"github.com/vernonedu/entrepreneurship-api/internal/domain/calendar"
	"github.com/vernonedu/entrepreneurship-api/pkg/commandbus"
	"github.com/vernonedu/entrepreneurship-api/pkg/eventbus"
)

type Handler struct {
	readRepo  calendar.ReadRepository
	writeRepo calendar.WriteRepository
	eventBus  eventbus.EventBus
}

func NewHandler(readRepo calendar.ReadRepository, writeRepo calendar.WriteRepository, eventBus eventbus.EventBus) *Handler {
	return &Handler{readRepo: readRepo, writeRepo: writeRepo, eventBus: eventBus}
}

func (h *Handler) Handle(ctx context.Context, cmd commandbus.Command) error {
	c, ok := cmd.(*DeleteCalendarEventCommand)
	if !ok {
		return ErrInvalidCommand
	}

	e, err := h.readRepo.GetByID(ctx, c.ID)
	if err != nil {
		return calendar.ErrCalendarEventNotFound
	}

	if !e.IsManual() {
		return calendar.ErrAutoGeneratedEventReadOnly
	}

	if err := h.writeRepo.Delete(ctx, c.ID); err != nil {
		log.Error().Err(err).Str("id", c.ID.String()).Msg("failed to delete calendar event")
		return err
	}
	return nil
}
