package update_calendar_event

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/rs/zerolog/log"

	"github.com/vernonedu/entrepreneurship-api/internal/domain/calendar"
	"github.com/vernonedu/entrepreneurship-api/pkg/commandbus"
	"github.com/vernonedu/entrepreneurship-api/pkg/eventbus"
)

type Handler struct {
	readRepo  calendar.ReadRepository
	writeRepo calendar.WriteRepository
	eventBus  eventbus.EventBus
}

func NewHandler(readRepo calendar.ReadRepository, writeRepo calendar.WriteRepository, eventBus eventbus.EventBus) *Handler {
	return &Handler{readRepo: readRepo, writeRepo: writeRepo, eventBus: eventBus}
}

func (h *Handler) Handle(ctx context.Context, cmd commandbus.Command) error {
	c, ok := cmd.(*UpdateCalendarEventCommand)
	if !ok {
		return ErrInvalidCommand
	}

	id, err := uuid.Parse(c.ID)
	if err != nil {
		return err
	}

	e, err := h.readRepo.GetByID(ctx, id)
	if err != nil {
		return calendar.ErrCalendarEventNotFound
	}

	if !e.IsManual() {
		return calendar.ErrAutoGeneratedEventReadOnly
	}

	startAt, err := time.Parse(time.RFC3339, c.StartAt)
	if err != nil {
		return err
	}
	endAt, err := time.Parse(time.RFC3339, c.EndAt)
	if err != nil {
		return err
	}

	e.Title = c.Title
	e.EventType = calendar.EventType(c.EventType)
	e.StartAt = startAt
	e.EndAt = endAt
	e.IsAllDay = c.IsAllDay

	if c.Description != "" {
		e.Description = &c.Description
	} else {
		e.Description = nil
	}
	if c.RecurrenceRule != "" {
		e.RecurrenceRule = &c.RecurrenceRule
	} else {
		e.RecurrenceRule = nil
	}
	if c.Location != "" {
		e.Location = &c.Location
	} else {
		e.Location = nil
	}

	if err := h.writeRepo.Update(ctx, e); err != nil {
		log.Error().Err(err).Str("id", c.ID).Msg("failed to update calendar event")
		return err
	}
	return nil
}
